import { Product, Category, Testimonial, Brand, GalleryItem, SiteSettings } from "./types";

export const siteSettings: SiteSettings = {
  companyName: "Ocean Lighting Solutions",
  tagline: "Importers & Dealers in LED Lighting, Electrical Items, and Interior Solutions",
  address: "591, Chilaw Road, Kattuwa, Negombo, Sri Lanka",
  email: "oceanlighting303@gmail.com",
  website: "www.oceanlighting.lk",
  telephone: "0314 300 657",
  mobile: "077 9 900 657",
  whatsapp: "94779900657",
  businessHours: {
    weekdays: "Monday – Friday: 8:00 AM – 6:00 PM",
    saturday: "Saturday: 8:00 AM – 4:00 PM",
    sunday: "Sunday: Closed",
  },
  socialMedia: {
    facebook: "https://facebook.com/oceanlighting",
    instagram: "https://instagram.com/oceanlighting",
  },
  heroTitle: "Illuminate Your World with Premium LED Solutions",
  heroSubtitle:
    "Sri Lanka's trusted importer and dealer of high-quality LED lighting, electrical items, and interior solutions. Transform your space with elegance.",
  aboutText:
    "Ocean Lighting Solutions has been serving Sri Lanka with premium lighting and electrical products for years. Based in Negombo, we import and distribute top-quality LED lighting, electrical items, and interior solutions to homes, businesses, and commercial spaces across the country.",
  metaDescription:
    "Ocean Lighting Solutions – Premium LED lighting, electrical items, and interior solutions in Negombo, Sri Lanka. Visit our showroom at 591, Chilaw Road, Kattuwa.",
};

export const categories: Category[] = [
  {
    id: "cat-1",
    name: "LED Lighting",
    slug: "led-lighting",
    description: "Energy-efficient LED solutions for every application",
    icon: "💡",
    image: "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=600&q=80",
  },
  {
    id: "cat-2",
    name: "Indoor Lighting",
    slug: "indoor-lighting",
    description: "Elegant indoor lighting for homes and offices",
    icon: "🏠",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
  },
  {
    id: "cat-3",
    name: "Outdoor Lighting",
    slug: "outdoor-lighting",
    description: "Durable outdoor lighting for gardens and facades",
    icon: "🌿",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
  },
  {
    id: "cat-4",
    name: "Electrical Items",
    slug: "electrical-items",
    description: "Quality electrical components and accessories",
    icon: "⚡",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&q=80",
  },
  {
    id: "cat-5",
    name: "Interior Solutions",
    slug: "interior-solutions",
    description: "Complete interior lighting design solutions",
    icon: "✨",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80",
  },
];

export const products: Product[] = [
  {
    id: "prod-1",
    name: "Premium LED Panel Light 60W",
    slug: "premium-led-panel-light-60w",
    category: "led-lighting",
    shortDescription: "Ultra-slim LED panel with uniform light distribution and high efficiency",
    description:
      "The Premium LED Panel Light 60W delivers exceptional brightness with a sleek, ultra-slim design. Perfect for offices, showrooms, and commercial spaces. Features advanced heat dissipation technology for extended lifespan and consistent performance.",
    images: [
      "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    specifications: {
      "Power": "60W",
      "Voltage": "220-240V AC",
      "Color Temperature": "4000K / 6500K",
      "Luminous Flux": "5400 lm",
      "CRI": ">80",
      "Lifespan": "50,000 hours",
      "Dimensions": "600 x 600 x 10mm",
      "IP Rating": "IP40",
    },
    features: [
      "Ultra-slim 10mm profile",
      "Flicker-free technology",
      "Energy saving up to 70%",
      "Easy installation",
      "2-year warranty",
    ],
    isFeatured: true,
    isNew: true,
    badge: "Best Seller",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "prod-2",
    name: "Crystal Chandelier – Luxury Series",
    slug: "crystal-chandelier-luxury-series",
    category: "indoor-lighting",
    shortDescription: "Stunning crystal chandelier for grand living spaces and hotels",
    description:
      "Elevate any space with our Luxury Crystal Chandelier. Handcrafted with premium K9 crystal elements, this chandelier creates breathtaking light patterns and adds a touch of opulence to any interior.",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
    ],
    specifications: {
      "Material": "K9 Crystal + Chrome Frame",
      "Diameter": "80cm",
      "Height": "60-120cm (adjustable)",
      "Bulb Type": "E14 LED",
      "Number of Lights": "12",
      "Max Wattage": "60W",
      "Voltage": "220-240V",
    },
    features: [
      "Premium K9 crystal",
      "Adjustable hanging height",
      "Compatible with dimmers",
      "Easy assembly",
      "Suitable for high ceilings",
    ],
    isFeatured: true,
    badge: "Premium",
    createdAt: "2024-01-02",
    updatedAt: "2024-01-02",
  },
  {
    id: "prod-3",
    name: "Solar Garden Spike Light",
    slug: "solar-garden-spike-light",
    category: "outdoor-lighting",
    shortDescription: "Eco-friendly solar-powered garden lights with auto on/off",
    description:
      "Transform your garden with our Solar Garden Spike Lights. Powered entirely by solar energy, these lights automatically turn on at dusk and off at dawn. Weather-resistant and maintenance-free.",
    images: [
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    ],
    specifications: {
      "Power Source": "Solar",
      "Battery": "1200mAh NiMH",
      "LED": "1W High Brightness",
      "Color Temperature": "3000K Warm White",
      "IP Rating": "IP65",
      "Charging Time": "6-8 hours",
      "Working Time": "8-10 hours",
    },
    features: [
      "100% solar powered",
      "Auto on/off sensor",
      "Weatherproof IP65",
      "No wiring required",
      "Eco-friendly",
    ],
    isFeatured: true,
    isNew: true,
    createdAt: "2024-01-03",
    updatedAt: "2024-01-03",
  },
  {
    id: "prod-4",
    name: "Smart LED Strip Light 5M",
    slug: "smart-led-strip-light-5m",
    category: "led-lighting",
    shortDescription: "RGB smart LED strip with app control and voice assistant support",
    description:
      "Create stunning ambient lighting with our Smart LED Strip Light. Control colors, brightness, and effects via smartphone app or voice commands. Perfect for TV backlighting, under-cabinet lighting, and accent lighting.",
    images: [
      "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&q=80",
    ],
    specifications: {
      "Length": "5 meters",
      "LEDs": "300 LEDs (60/m)",
      "Power": "24W",
      "Voltage": "12V DC",
      "Colors": "16 million RGB colors",
      "Connectivity": "WiFi 2.4GHz",
      "Compatibility": "Alexa, Google Home",
    },
    features: [
      "16 million color options",
      "App & voice control",
      "Music sync mode",
      "Cuttable every 3 LEDs",
      "Self-adhesive backing",
    ],
    isFeatured: true,
    isNew: true,
    badge: "Smart",
    createdAt: "2024-01-04",
    updatedAt: "2024-01-04",
  },
  {
    id: "prod-5",
    name: "Industrial High Bay LED 150W",
    slug: "industrial-high-bay-led-150w",
    category: "led-lighting",
    shortDescription: "High-performance LED for warehouses, factories, and large spaces",
    description:
      "Designed for demanding industrial environments, our High Bay LED delivers powerful illumination with exceptional energy efficiency. Ideal for warehouses, factories, sports halls, and large commercial spaces.",
    images: [
      "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80",
    ],
    specifications: {
      "Power": "150W",
      "Voltage": "100-277V AC",
      "Luminous Flux": "18,000 lm",
      "Color Temperature": "5000K",
      "CRI": ">80",
      "Beam Angle": "120°",
      "IP Rating": "IP65",
      "Lifespan": "60,000 hours",
    },
    features: [
      "High lumen output",
      "Industrial grade IP65",
      "Wide voltage range",
      "Instant start, no warm-up",
      "5-year warranty",
    ],
    isFeatured: false,
    createdAt: "2024-01-05",
    updatedAt: "2024-01-05",
  },
  {
    id: "prod-6",
    name: "Modern Track Lighting System",
    slug: "modern-track-lighting-system",
    category: "indoor-lighting",
    shortDescription: "Adjustable track lighting for retail, galleries, and modern interiors",
    description:
      "Our Modern Track Lighting System offers flexible, directional lighting perfect for highlighting artwork, merchandise, or architectural features. Fully adjustable heads allow precise light positioning.",
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
    ],
    specifications: {
      "Track Length": "1m / 2m / 3m",
      "Spotlight Power": "10W each",
      "Color Temperature": "3000K / 4000K",
      "Beam Angle": "24° / 36°",
      "Voltage": "220-240V",
      "Finish": "Matte Black / White",
    },
    features: [
      "360° adjustable heads",
      "Modular design",
      "Compatible with dimmers",
      "Easy installation",
      "Multiple finish options",
    ],
    isFeatured: true,
    badge: "Popular",
    createdAt: "2024-01-06",
    updatedAt: "2024-01-06",
  },
  {
    id: "prod-7",
    name: "Waterproof LED Flood Light 50W",
    slug: "waterproof-led-flood-light-50w",
    category: "outdoor-lighting",
    shortDescription: "Powerful outdoor flood light for security and landscape lighting",
    description:
      "Illuminate large outdoor areas with our Waterproof LED Flood Light. Built to withstand harsh weather conditions with IP66 rating, it's perfect for security lighting, building facades, and landscape illumination.",
    images: [
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    ],
    specifications: {
      "Power": "50W",
      "Voltage": "220-240V AC",
      "Luminous Flux": "4500 lm",
      "Color Temperature": "6500K",
      "IP Rating": "IP66",
      "Beam Angle": "120°",
      "Lifespan": "50,000 hours",
    },
    features: [
      "IP66 weatherproof",
      "Wide beam angle",
      "Corrosion-resistant housing",
      "Easy wall mounting",
      "3-year warranty",
    ],
    isFeatured: false,
    createdAt: "2024-01-07",
    updatedAt: "2024-01-07",
  },
  {
    id: "prod-8",
    name: "MCB Distribution Board",
    slug: "mcb-distribution-board",
    category: "electrical-items",
    shortDescription: "Premium MCB distribution board for residential and commercial use",
    description:
      "Our MCB Distribution Board provides reliable circuit protection for residential and commercial electrical installations. Features high-quality miniature circuit breakers with precise trip characteristics.",
    images: [
      "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80",
    ],
    specifications: {
      "Ways": "4 / 8 / 12 / 16 / 20",
      "Voltage": "240/415V",
      "Current Rating": "63A / 100A",
      "IP Rating": "IP40",
      "Material": "Flame-retardant ABS",
      "Standard": "IEC 60439",
    },
    features: [
      "Flame-retardant housing",
      "DIN rail mounting",
      "Transparent cover",
      "Easy cable management",
      "Multiple configurations",
    ],
    isFeatured: false,
    createdAt: "2024-01-08",
    updatedAt: "2024-01-08",
  },
  {
    id: "prod-9",
    name: "Pendant Light – Nordic Design",
    slug: "pendant-light-nordic-design",
    category: "interior-solutions",
    shortDescription: "Minimalist Nordic pendant light for dining rooms and cafes",
    description:
      "Inspired by Scandinavian design principles, our Nordic Pendant Light combines simplicity with elegance. The warm glow creates an inviting atmosphere perfect for dining areas, cafes, and modern interiors.",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    specifications: {
      "Material": "Aluminum + Fabric Cord",
      "Shade Diameter": "30cm",
      "Cord Length": "1.5m (adjustable)",
      "Bulb Type": "E27 LED",
      "Max Wattage": "40W",
      "Finish": "Matte Black / Gold / White",
    },
    features: [
      "Minimalist Scandinavian design",
      "Adjustable cord length",
      "Multiple color options",
      "Compatible with dimmers",
      "Easy installation",
    ],
    isFeatured: true,
    isNew: true,
    badge: "New Arrival",
    createdAt: "2024-01-09",
    updatedAt: "2024-01-09",
  },
  {
    id: "prod-10",
    name: "LED Downlight 12W Recessed",
    slug: "led-downlight-12w-recessed",
    category: "indoor-lighting",
    shortDescription: "Slim recessed LED downlight for clean, modern ceiling installations",
    description:
      "Our LED Downlight delivers crisp, focused illumination with a sleek recessed design. Perfect for living rooms, bedrooms, kitchens, and commercial spaces where clean aesthetics are paramount.",
    images: [
      "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&q=80",
    ],
    specifications: {
      "Power": "12W",
      "Voltage": "220-240V",
      "Color Temperature": "3000K / 4000K / 6500K",
      "Luminous Flux": "1080 lm",
      "CRI": ">90",
      "Cut-out": "Ø95mm",
      "Lifespan": "50,000 hours",
    },
    features: [
      "High CRI >90",
      "Flicker-free",
      "Slim profile design",
      "Multiple CCT options",
      "3-year warranty",
    ],
    isFeatured: false,
    createdAt: "2024-01-10",
    updatedAt: "2024-01-10",
  },
  {
    id: "prod-11",
    name: "Wall Sconce – Art Deco",
    slug: "wall-sconce-art-deco",
    category: "interior-solutions",
    shortDescription: "Elegant Art Deco wall sconce for luxury interiors and hotels",
    description:
      "Add a touch of timeless elegance with our Art Deco Wall Sconce. Featuring geometric patterns and premium brass finish, this fixture is perfect for hotel lobbies, luxury residences, and upscale restaurants.",
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
    ],
    specifications: {
      "Material": "Brass + Glass",
      "Dimensions": "15 x 25cm",
      "Bulb Type": "E14 LED",
      "Max Wattage": "20W",
      "Finish": "Antique Brass / Chrome",
      "IP Rating": "IP20",
    },
    features: [
      "Premium brass construction",
      "Art Deco geometric design",
      "Frosted glass diffuser",
      "Easy wall mounting",
      "Suitable for indoor use",
    ],
    isFeatured: false,
    createdAt: "2024-01-11",
    updatedAt: "2024-01-11",
  },
  {
    id: "prod-12",
    name: "LED Street Light 80W",
    slug: "led-street-light-80w",
    category: "outdoor-lighting",
    shortDescription: "High-efficiency LED street light for roads and parking areas",
    description:
      "Our LED Street Light provides powerful, uniform illumination for roads, parking lots, and public spaces. Designed for long-term outdoor use with superior weather resistance and minimal maintenance requirements.",
    images: [
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    ],
    specifications: {
      "Power": "80W",
      "Voltage": "100-277V AC",
      "Luminous Flux": "9600 lm",
      "Color Temperature": "5700K",
      "IP Rating": "IP66",
      "IK Rating": "IK09",
      "Lifespan": "70,000 hours",
    },
    features: [
      "IP66 + IK09 protection",
      "Photocell compatible",
      "Surge protection 10kV",
      "Aluminum die-cast housing",
      "5-year warranty",
    ],
    isFeatured: false,
    createdAt: "2024-01-12",
    updatedAt: "2024-01-12",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "test-1",
    name: "Priya Jayawardena",
    role: "Interior Designer",
    company: "Luxe Interiors Colombo",
    content:
      "Ocean Lighting Solutions has been my go-to supplier for all lighting projects. Their product quality is exceptional and the team is incredibly knowledgeable. My clients are always impressed with the results.",
    rating: 5,
  },
  {
    id: "test-2",
    name: "Chaminda Perera",
    role: "Hotel Manager",
    company: "Serenity Beach Resort",
    content:
      "We renovated our entire hotel lighting with Ocean Lighting Solutions. The transformation was remarkable. Professional service, premium products, and excellent after-sales support. Highly recommended!",
    rating: 5,
  },
  {
    id: "test-3",
    name: "Nimal Fernando",
    role: "Homeowner",
    company: "Negombo",
    content:
      "Visited their showroom and was amazed by the variety. The staff helped me choose the perfect lighting for my new home. The installation was smooth and the results are stunning. Great value for money!",
    rating: 5,
  },
  {
    id: "test-4",
    name: "Dilani Wickramasinghe",
    role: "Architect",
    company: "DW Architecture",
    content:
      "As an architect, I need reliable suppliers who understand design. Ocean Lighting Solutions consistently delivers premium products on time. Their LED solutions have transformed many of my projects.",
    rating: 5,
  },
];

export const brands: Brand[] = [
  { id: "brand-1", name: "Philips", logo: "/brands/philips.svg" },
  { id: "brand-2", name: "Osram", logo: "/brands/osram.svg" },
  { id: "brand-3", name: "Havells", logo: "/brands/havells.svg" },
  { id: "brand-4", name: "Wipro", logo: "/brands/wipro.svg" },
  { id: "brand-5", name: "Syska", logo: "/brands/syska.svg" },
  { id: "brand-6", name: "Crompton", logo: "/brands/crompton.svg" },
];

export const galleryItems: GalleryItem[] = [
  {
    id: "gal-1",
    title: "Luxury Hotel Lobby",
    description: "Complete lighting transformation for a 5-star hotel",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    category: "Commercial",
  },
  {
    id: "gal-2",
    title: "Modern Office Space",
    description: "Energy-efficient LED panel installation",
    image: "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&q=80",
    category: "Commercial",
  },
  {
    id: "gal-3",
    title: "Residential Living Room",
    description: "Elegant chandelier and ambient lighting design",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
    category: "Residential",
  },
  {
    id: "gal-4",
    title: "Garden Landscape",
    description: "Solar-powered outdoor lighting installation",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    category: "Outdoor",
  },
  {
    id: "gal-5",
    title: "Restaurant Interior",
    description: "Warm ambient lighting for dining experience",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    category: "Commercial",
  },
  {
    id: "gal-6",
    title: "Retail Showroom",
    description: "Track lighting for product display",
    image: "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&q=80",
    category: "Commercial",
  },
];
