import { Product, Category, Testimonial, Brand, GalleryItem, SiteSettings } from "./types";

export const siteSettings: SiteSettings = {
  companyName: "OCEAN Lighting Solutions",
  tagline: "Premium LED Lighting & OCEANA Luxury Bathware",
  address: "591, Chilaw Road, Kattuwa, Negombo, Sri Lanka",
  email: "oceanlighting303@gmail.com",
  website: "www.oceanlighting.lk",
  telephone: "0314 300 657",
  mobile: "077 9 900 657",
  whatsapp: "94779900657",
  businessHours: {
    weekdays: "Monday – Friday: 8:00 AM – 6:00 PM",
    saturday: "Saturday: 8:00 AM – 4:00 PM",
    sunday: "Sunday: Closed",
  },
  socialMedia: {
    facebook: "https://facebook.com/oceanlighting",
    instagram: "https://instagram.com/oceanlighting",
  },
  heroTitle: "Elevate Your Spaces with Exquisite Light & Water",
  heroSubtitle:
    "Sri Lanka's trusted partner for high-end LED lighting, imported electrical fixtures, and designer OCEANA bathware solutions. Experience the ultimate harmony of elegance and innovation.",
  aboutText:
    "OCEAN Lighting Solutions is Sri Lanka's premium destination for luxury LED lighting, electrical installations, and exclusive agent for the OCEANA luxury bathware and sanitaryware collection. Operating from our grand showroom in Negombo, we import and distribute elite products that blend state-of-the-art technology with breathtaking design. We cater to luxury homes, boutique hotels, and landmark commercial spaces across the island.",
  metaDescription:
    "OCEAN Lighting Solutions – Premium LED lighting, electrical setups, and designer OCEANA bathware in Negombo, Sri Lanka. Elevate your architecture with our signature collections.",
};

export const categories: Category[] = [
  {
    id: "cat-1",
    name: "LED Indoor Lighting",
    slug: "led-indoor-lighting",
    description: "Elegant interior lighting from luxury chandeliers to architectural downlights.",
    icon: "💡",
    image: "https://images.unsplash.com/photo-1543248939-ff40856f65d4?w=600&q=80",
  },
  {
    id: "cat-2",
    name: "LED Outdoor Lighting",
    slug: "led-outdoor-lighting",
    description: "Durable and weather-resistant facade, landscape, and garden light fixtures.",
    icon: "🌿",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
  },
  {
    id: "cat-3",
    name: "Luxury Sanitaryware",
    slug: "luxury-sanitaryware",
    description: "Modern smart toilets, designer washbasins, and premium ceramic suites.",
    icon: "🚽",
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
  },
  {
    id: "cat-4",
    name: "Designer Showers & Faucets",
    slug: "designer-showers-faucets",
    description: "Thermostatic rain shower columns and high-end polished brassware.",
    icon: "🚿",
    image: "https://images.unsplash.com/photo-1585128792020-803d29415281?w=600&q=80",
  },
  {
    id: "cat-5",
    name: "Premium Bathtubs & Jacuzzis",
    slug: "premium-bathtubs",
    description: "Freestanding acrylic bathtubs, whirlpool spas, and massage tubs.",
    icon: "🛁",
    image: "https://images.unsplash.com/photo-1584622781564-1d987f7333c1?w=600&q=80",
  },
  {
    id: "cat-6",
    name: "Smart Mirrors & Accessories",
    slug: "bathroom-accessories",
    description: "Smart anti-fog LED mirrors, premium towel rails, and designer vanity additions.",
    icon: "✨",
    image: "https://images.unsplash.com/photo-1620626011761-996317b8d101?w=600&q=80",
  },
];

export const products: Product[] = [
  {
    id: "prod-1",
    name: "OCEANA Aura Smart Toilet – Royal Suite",
    slug: "aura-smart-toilet-royal-suite",
    category: "luxury-sanitaryware",
    shortDescription: "Intelligent ceramic toilet with integrated bidet, heated seat, and touchless control",
    description:
      "The Aura Smart Toilet represents the pinnacle of modern bathroom luxury. Features a heated seat with adjustable temperature, customizable front and rear wash cycles, warm air dryer, automatic deodorizer, and touchless motion-activated lid. Crafted from high-density antibacterial ceramic with a sleek rimless design.",
    images: [
      "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80",
    ],
    specifications: {
      "Material": "Vitreous China (Antibacterial Glaze)",
      "Flushing System": "Siphon Jet (Tornado Flush)",
      "Water Pressure": "0.07 - 0.75 MPa",
      "Voltage": "220-240V AC",
      "Seat Heating": "4 levels adjustable",
      "Water Heating": "Instantaneous thermal heater",
      "Dimensions": "680 x 410 x 470mm",
      "IP Rating": "IPX4",
    },
    features: [
      "Motion-activated lid opening and closing",
      "Dynamic Tornado dual-flush system",
      "Self-cleaning stainless steel nozzle",
      "LED nightlight and digital display",
      "Eco-friendly power saving mode",
    ],
    isFeatured: true,
    isNew: true,
    badge: "Signature",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "prod-2",
    name: "Crystal Chandelier – Luxury Series",
    slug: "crystal-chandelier-luxury-series",
    category: "led-indoor-lighting",
    shortDescription: "Stunning crystal chandelier with premium K9 elements for grand spaces",
    description:
      "Elevate your grand living space, dining room, or hotel lobby with our Luxury Crystal Chandelier. Handcrafted with precision-cut K9 crystal elements that refract light into dazzling spectrums. Equipped with a gold-finished stainless steel frame that guarantees stability and timeless elegance.",
    images: [
      "https://images.unsplash.com/photo-1543248939-ff40856f65d4?w=800&q=80",
      "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&q=80",
    ],
    specifications: {
      "Material": "K9 Crystal + Plated Stainless Steel",
      "Diameter": "95cm",
      "Height": "70-130cm (adjustable suspension)",
      "Bulb Type": "E14 LED (Warm White included)",
      "Number of Lights": "18",
      "Max Wattage": "90W",
      "Voltage": "220-240V",
    },
    features: [
      "Authentic K9 crystal elements",
      "Polished champagne gold plating",
      "Dimmable controller compatible",
      "Adjustable steel suspension cords",
      "Includes 3-year warranty protection",
    ],
    isFeatured: true,
    badge: "Exclusive",
    createdAt: "2024-01-02",
    updatedAt: "2024-01-02",
  },
  {
    id: "prod-3",
    name: "OCEANA Thermostatic Rain Shower Column – Brushed Gold",
    slug: "thermostatic-rain-shower-column-brushed-gold",
    category: "designer-showers-faucets",
    shortDescription: "Luxury thermostatic mixer valve, overhead rain shower, and multi-mode hand spray",
    description:
      "Bring the wellness spa experience home with the OCEANA Thermostatic Shower Column. Engineered from solid lead-free brass with a premium brushed gold PVD finish. The built-in safety valve locks water at a precise 38°C to prevent scalding, while the expansive rain shower face delivers a soothing droplet flow.",
    images: [
      "https://images.unsplash.com/photo-1604014237800-1c9102c219da?w=800&q=80",
    ],
    specifications: {
      "Valve Body": "Solid DZR Brass",
      "Finish": "Brushed Gold PVD",
      "Overhead Shower Size": "300 x 300mm",
      "Temp Control": "Thermostatic (38°C Safety Lock)",
      "Hose Length": "1.5m anti-twist",
      "Min Pressure": "1.0 Bar",
      "Connection Size": "G 1/2 standard",
    },
    features: [
      "Precision thermostatic temperature control",
      "Brushed Gold PVD scratch-resistant finish",
      "Anti-lime silicon nozzles for easy cleaning",
      "Slimline stainless steel overhead shower",
      "3-way diverter (Rain, Hand shower, Tub spout)",
    ],
    isFeatured: true,
    isNew: true,
    badge: "New Arrival",
    createdAt: "2024-01-03",
    updatedAt: "2024-01-03",
  },
  {
    id: "prod-4",
    name: "OCEANA Venezia Freestanding Acrylic Bathtub",
    slug: "venezia-freestanding-acrylic-bathtub",
    category: "premium-bathtubs",
    shortDescription: "Elegant double-ended freestanding tub with overflow system",
    description:
      "An artistic center-piece for your master bath. The Venezia Freestanding Bathtub features a double-ended design, letting you recline comfortably at either end. Manufactured using premium sanitary-grade acrylic sheet reinforced with high-density fiberglass for maximum heat retention and structural stability.",
    images: [
      "https://images.unsplash.com/photo-1584622781564-1d987f7333c1?w=800&q=80",
    ],
    specifications: {
      "Material": "Lucite Sanitary Acrylic",
      "Reinforcement": "Fiberglass + Steel support frame",
      "Length": "1700mm",
      "Width": "800mm",
      "Depth": "600mm",
      "Water Capacity": "240 Liters",
      "Waste Finish": "Polished Chrome (Push-down)",
    },
    features: [
      "Smooth, non-porous easy-to-clean surface",
      "Double-walled thermal insulation",
      "Integrated chrome overflow and pop-up waste",
      "Adjustable leveling feet underneath frame",
      "Resistant to scratching and yellowing",
    ],
    isFeatured: true,
    badge: "Premium",
    createdAt: "2024-01-04",
    updatedAt: "2024-01-04",
  },
  {
    id: "prod-5",
    name: "OCEANA Lumina LED Smart Anti-Fog Mirror",
    slug: "lumina-led-smart-anti-fog-mirror",
    category: "bathroom-accessories",
    shortDescription: "Elegant backlit bathroom mirror with touch sensor, anti-fog heater, and color adjustment",
    description:
      "Transform your daily vanity routine with the Lumina Smart LED Mirror. Outfitted with high-lumen backlight strips, it provides shadow-free task illumination. A built-in demister pad automatically keeps the central glass steam-free. Choose between warm, natural, and cool lighting with a simple touch.",
    images: [
      "https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800&q=80",
    ],
    specifications: {
      "Glass Type": "5mm Copper-Free HD Mirror",
      "LED Strip": "120 LEDs/m (High CRI >90)",
      "Colors": "3000K / 4000K / 6000K adjustable",
      "Input Voltage": "220-240V AC",
      "Heating Pad": "Built-in (Auto off 1 hour)",
      "Size": "800 x 600mm (Vertical/Horizontal)",
      "IP Rating": "IP44 Waterproof",
    },
    features: [
      "Touch sensors with memory function",
      "Rapid heat anti-fog demister pad",
      "Seamless dimming and color switching",
      "CRI >90 for realistic skin reflections",
      "Aluminum back frame for easy mounting",
    ],
    isFeatured: true,
    badge: "Best Seller",
    createdAt: "2024-01-05",
    updatedAt: "2024-01-05",
  },
  {
    id: "prod-6",
    name: "Titan Waterproof LED Flood Light 100W",
    slug: "titan-waterproof-led-flood-light-100w",
    category: "led-outdoor-lighting",
    shortDescription: "Ultra-bright commercial-grade exterior flood light with IP66 rating",
    description:
      "A heavy-duty outdoor lighting solution. The Titan Flood Light produces massive illumination while using up to 80% less energy. Enclosed in a robust die-cast aluminum casing with a tempered glass cover. Perfect for building facades, large landscapes, parking yards, and security lighting.",
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
    ],
    specifications: {
      "Power": "100W",
      "Luminous Flux": "11,500 lm",
      "Color Temp": "6000K Cool White",
      "IP Rating": "IP66 (Weatherproof)",
      "IK Rating": "IK08 Impact Resistant",
      "Voltage Range": "100-265V AC",
      "Lifespan": "60,000 hours",
    },
    features: [
      "Die-cast aluminum heat-dissipating ribs",
      "Anti-glare optical polycarbonate lens",
      "120° wide coverage beam angle",
      "U-shaped adjustable mounting bracket",
      "Built-in 6kV surge protector safety",
    ],
    isFeatured: true,
    createdAt: "2024-01-06",
    updatedAt: "2024-01-06",
  },
  {
    id: "prod-7",
    name: "OCEANA Cascade Waterfall Basin Faucet – Matte Black",
    slug: "cascade-waterfall-basin-faucet-matte-black",
    category: "designer-showers-faucets",
    shortDescription: "Designer single-handle basin mixer with wide waterfall spout",
    description:
      "A statement faucet that redefines luxury water delivery. Emitting a elegant, smooth sheet of water simulating a natural waterfall. Precision engineered with a Sedal ceramic cartridge for drip-free longevity. The matte black electroplated coating resists fingerprints and rust.",
    images: [
      "https://images.unsplash.com/photo-1585128792020-803d29415281?w=800&q=80",
    ],
    specifications: {
      "Body Material": "H59 Solid Brass",
      "Finish": "Matte Black Electroplated",
      "Spout Style": "Wide Waterfall",
      "Cartridge": "Ceramic Disc Valve",
      "Overall Height": "180mm",
      "Spout Reach": "120mm",
      "Hoses Included": "2x 60cm flexible hot/cold",
    },
    features: [
      "Modern minimalist waterfall design",
      "Smooth single-lever water/temp handle",
      "Drip-free ceramic disc cartridge test 500k",
      "Corrosion-resistant matte finish coating",
      "Eco-water saving restrictor pre-installed",
    ],
    isFeatured: false,
    isNew: true,
    createdAt: "2024-01-07",
    updatedAt: "2024-01-07",
  },
  {
    id: "prod-8",
    name: "Opaline Pendant Light – Nordic Design",
    slug: "opaline-pendant-light-nordic-design",
    category: "led-indoor-lighting",
    shortDescription: "Minimalist Scandinavian design with opaline glass orb and gold accents",
    description:
      "Crafted with Nordic simplicity, this hanging pendant fixture displays a frosted opaline glass sphere suspended from a luxurious brass-finished rod. Diffuses a soft, warm ambient light, making it the perfect centerpiece for kitchen islands, dining tables, and trendy cafes.",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    specifications: {
      "Material": "Opal Glass Shade + Brass Hardware",
      "Globe Diameter": "25cm",
      "Cord Length": "1.8 meters (adjustable wire)",
      "Bulb Holder": "E27 LED compatibility",
      "Max Wattage": "40W",
      "Voltage": "220-240V",
    },
    features: [
      "Scandinavian luxury styling",
      "Diffused glare-free frosted glass orb",
      "Brushed brass finish details",
      "Adjustable textile fabric cord length",
      "Quick and easy installation kit",
    ],
    isFeatured: true,
    isNew: true,
    badge: "Popular",
    createdAt: "2024-01-08",
    updatedAt: "2024-01-08",
  },
  {
    id: "prod-9",
    name: "OCEANA Monolith Pedestal Washbasin – Nero Marquina",
    slug: "monolith-luxury-washbasin-nero-marquina",
    category: "luxury-sanitaryware",
    shortDescription: "Pedestal washbasin carved from high-grade natural-look composite marble",
    description:
      "A bold architectural piece. The Monolith Washbasin is sculpted with absolute precision, displaying stunning white veins running through a deep black core. Finished with a satin nano-sealant that makes the surface impermeable to dirt, staining, and soap residue.",
    images: [
      "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80",
    ],
    specifications: {
      "Material": "Sanitary Grade Composite Marble",
      "Finish": "Nero Marquina Black (Satin Matte)",
      "Type": "Free-standing Pedestal Sink",
      "Overflow": "Not included (Free-flow required)",
      "Drain Size": "45mm standard",
      "Dimensions": "450 x 450 x 850mm",
      "Weight": "42 kg",
    },
    features: [
      "Pedestal pillar modern structure",
      "Hydrophobic scratch-resistant nano glaze",
      "Resistant to high temperature thermal shock",
      "Stunning organic marble aesthetics",
      "Solid, heavy structural stance",
    ],
    isFeatured: false,
    isNew: true,
    createdAt: "2024-01-09",
    updatedAt: "2024-01-09",
  },
  {
    id: "prod-10",
    name: "Aero-Sleek LED Downlight 12W",
    slug: "aero-sleek-led-downlight-12w",
    category: "led-indoor-lighting",
    shortDescription: "Ultra-slim recessed aluminum downlight with tri-color CCT changing",
    description:
      "The Aero-Sleek Recessed Downlight fits flush into ceilings with a depth of only 20mm. Features a toggle switch to select between Warm White, Neutral White, and Cool White prior to installation. High CRI >90 ensures vivid interior color representation.",
    images: [
      "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&q=80",
    ],
    specifications: {
      "Power": "12W",
      "Luminous Flux": "1080 lm",
      "Color Temp": "3000K / 4000K / 6500K CCT Changeable",
      "CRI": ">90 for high clarity",
      "Cut-out Hole": "Ø105-115mm",
      "Thickness": "20mm ultra-slim",
      "Driver": "Isolated IC Constant Current",
    },
    features: [
      "Flush-ceiling clean integration look",
      "Integrated switch for CCT color changing",
      "Flicker-free eye protect technology",
      "Die-cast aluminum casing thermal cooling",
      "Up to 85% energy efficiency savings",
    ],
    isFeatured: false,
    createdAt: "2024-01-10",
    updatedAt: "2024-01-10",
  },
  {
    id: "prod-11",
    name: "Solar Path & Lawn Spike Light",
    slug: "solar-path-lawn-spike-light",
    category: "led-outdoor-lighting",
    shortDescription: "Solar powered brass-finish spike light for gardens and path illumination",
    description:
      "Eco-luxury lighting for your lawns and garden pathways. Equipped with a high-efficiency monocrystalline solar panel and lithium-ion rechargeable battery. Automatically powers on as sunset drops and projects a gorgeous starburst light pattern onto the ground.",
    images: [
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&q=80",
    ],
    specifications: {
      "Solar Panel": "5V 2W Monocrystalline",
      "Battery": "3.7V 2000mAh Li-ion",
      "LED": "3W Osram Filament",
      "Color Temp": "2700K Warm Gold",
      "Charging Time": "5-6 hours sunshine",
      "Run Time": "10-12 hours fully charged",
      "IP Rating": "IP65 Weatherproof",
    },
    features: [
      "100% solar powered grid-free installation",
      "Polished metallic brass design finish",
      "Heavy-duty ABS ground spike tool",
      "Built-in light sensor for auto on/off",
      "Tempered solar glass diffuser casing",
    ],
    isFeatured: false,
    isNew: true,
    createdAt: "2024-01-11",
    updatedAt: "2024-01-11",
  },
  {
    id: "prod-12",
    name: "OCEANA Aura Smart Vanity LED Mirror Cabinet",
    slug: "aura-smart-vanity-led-mirror-cabinet",
    category: "bathroom-accessories",
    shortDescription: "Wall-mount aluminum cabinet with LED lighting, digital clock, and shaver socket",
    description:
      "Double up on storage and luxury. The Aura Mirror Cabinet is made from moisture-proof space-grade aluminum. It is fronted by dual double-sided mirror doors embedded with vertical frosted light bars. Internally equipped with glass shelving, a shaver charging socket, and a sensor switch.",
    images: [
      "https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800&q=80",
    ],
    specifications: {
      "Cabinet Material": "Anodized Space-Grade Aluminum",
      "Mirror Glass": "Dual HD copper-free mirrors",
      "LED Strips": "Front facing + Interior lighting",
      "Socket": "Shaver charging socket 230V",
      "Shelves": "3x adjustable tempered glass shelves",
      "Dimensions": "700 x 650 x 135mm",
      "IP Rating": "IP44 Splashproof",
    },
    features: [
      "Double door mirrored cabinet storage space",
      "Integrated digital clock and temperature dial",
      "Internal shaver/toothbrush socket built-in",
      "Soft-closing buffer hinges system",
      "Infrared hand-wave sensor switch",
    ],
    isFeatured: false,
    isNew: true,
    createdAt: "2024-01-12",
    updatedAt: "2024-01-12",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "test-1",
    name: "Priya Jayawardena",
    role: "Interior Designer",
    company: "Luxe Interiors Colombo",
    content:
      "OCEANA has completely changed my design workflow. Their lighting creates perfect moods, and their bathware matches the high luxury expectations of my premium clients. Outstanding quality and support.",
    rating: 5,
  },
  {
    id: "test-2",
    name: "Chaminda Perera",
    role: "Hotel Manager",
    company: "Serenity Beach Resort",
    content:
      "We outfitted our VIP villas with OCEANA's smart toilets, rainfall showers, and indoor pendant lighting. The guest feedback has been incredible. Exceptional products, professional service, and great durability.",
    rating: 5,
  },
  {
    id: "test-3",
    name: "Nimal Fernando",
    role: "Homeowner",
    company: "Negombo",
    content:
      "Visiting the Negombo showroom was a fantastic experience. The team helped me map out both my living room lighting layout and my bathrooms sanitary setup. The gold finish showers look majestic, and lighting is gorgeous.",
    rating: 5,
  },
  {
    id: "test-4",
    name: "Dilani Wickramasinghe",
    role: "Architect",
    company: "DW Architecture",
    content:
      "As an architect, finding a brand that matches lighting expertise with luxury bathware imports is rare. OCEANA consistently provides top-tier products, custom specs, and reliable warranties for my projects.",
    rating: 5,
  },
];

export const brands: Brand[] = [
  { id: "brand-1", name: "TOTO", logo: "/brands/toto.svg" },
  { id: "brand-2", name: "Grohe", logo: "/brands/grohe.svg" },
  { id: "brand-3", name: "Kohler", logo: "/brands/kohler.svg" },
  { id: "brand-4", name: "Roca", logo: "/brands/roca.svg" },
  { id: "brand-5", name: "Philips", logo: "/brands/philips.svg" },
  { id: "brand-6", name: "Osram", logo: "/brands/osram.svg" },
  { id: "brand-7", name: "Jaquar", logo: "/brands/jaquar.svg" },
  { id: "brand-8", name: "Panasonic", logo: "/brands/panasonic.svg" },
];

export const galleryItems: GalleryItem[] = [
  {
    id: "gal-1",
    title: "Luxury Hotel Suite Bathroom",
    description: "Complete bathware and lighting setup for a 5-star hotel villa",
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80",
    category: "Commercial",
  },
  {
    id: "gal-2",
    title: "Modern Office Reception",
    description: "Architectural line LED panels and downlight layout",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
    category: "Commercial",
  },
  {
    id: "gal-3",
    title: "Residential Penthouse Bath",
    description: "Freestanding bathtub and warm ambient LED strip setup",
    image: "https://images.unsplash.com/photo-1584622781564-1d987f7333c1?w=800&q=80",
    category: "Residential",
  },
  {
    id: "gal-4",
    title: "Luxury Garden Pathways",
    description: "Solar-powered lawn light illumination and spike lights",
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&q=80",
    category: "Outdoor",
  },
  {
    id: "gal-5",
    title: "Boutique Restaurant Dining",
    description: "Opal glass pendant lighting and cozy brass features",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    category: "Commercial",
  },
  {
    id: "gal-6",
    title: "Minimalist Master Bath Suite",
    description: "Smart anti-fog mirrors and matte black waterfall tap faucets",
    image: "https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800&q=80",
    category: "Residential",
  },
];
